### ISSUE TITLE
C++ Clang flexible array member with non-trivial destruction error with ImGui

### ISSUE THREAD

**Issue by spacepluk** [nimgl/nimgl#38]
I'm getting this when I try the imgui example on macOS (10.14.6):

```
  Verifying dependencies for nimdsp@0.1.0
    Reading official package list
   Checking for nimgl@>= 1.0.0
      Info: Dependency on nimgl@>= 1.0.0 already satisfied
  Verifying dependencies for nimgl@1.1.0
   Building nimdsp/nimdsp using cpp backend
     Error: Build failed for package: nimdsp
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/Users/spacepluk/.nimble/bin/nim" cpp --noNimblePath -d:NimblePkgVersion=0.1.0 --path:"/Users/spacepluk/Hacking/nimgl/src"  -o:"/Users/spacepluk/Hacking/nimdsp/nimdsp" "/Users/spacepluk/Hacking/nimdsp/src/nimdsp.nim"
        ... Output: Hint: used config file '/Users/spacepluk/.choosenim/toolchains/nim-1.0.4/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: widestrs [Processing]
        ... Hint: io [Processing]
        ... Hint: nimdsp [Processing]
        ... Hint: imgui [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: macros [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: impl_opengl [Processing]
        ... Hint: opengl [Processing]
        ... Hint: dynlib [Processing]
        ... Hint: posix [Processing]
        ... Hint: impl_glfw [Processing]
        ... Hint: glfw [Processing]
        ... Hint: logo [Processing]
        ... Hint: native [Processing]
        ... /Users/spacepluk/Hacking/nimdsp/src/nimdsp.nim(24, 7) Hint: 'io' is declared but not used [XDeclaredButNotUsed]
        ... CC: ../../nimgl/src/nimgl/imgui/impl_opengl.nim
        ... CC: nimdsp.nim
        ... Error: execution of an external compiler program 'clang++ -c  -w -I/Users/spacepluk/Hacking/nimgl/src/nimgl/private/cimgui -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1 -D_GLFW_COCOA -D_GLFW_USE_CHDIR -D_GLFW_USE_MENUBAR -D_GLFW_USE_RETINA -DGLFW_EXPOSE_NATIVE_COCOA -DGLFW_EXPOSE_NATIVE_NSGL  -I/Users/spacepluk/.choosenim/toolchains/nim-1.0.4/lib -I/Users/spacepluk/Hacking/nimdsp/src -o /Users/spacepluk/.cache/nim/nimdsp_d/@mnimdsp.nim.cpp.o /Users/spacepluk/.cache/nim/nimdsp_d/@mnimdsp.nim.cpp' failed with exit code: 1
        ... /Users/spacepluk/.cache/nim/nimdsp_d/@mnimdsp.nim.cpp:140:15: error: flexible array member 'Data' of type 'ImDrawChannel []' with non-trivial destruction
        ... ImDrawChannel Data[SEQ_DECL_SIZE];
        ...               ^
        ... 1 error generated.
```

```
Nim Compiler Version 1.0.4 [MacOSX: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

This is my first contact with nim though, so I might be doing something wrong.

**Comment by lmariscal** [comment]
The problem seems to be that clang is being pedantic with a data type. I have isolated the issue to line 433 of the imgui.nim file. Changing from an object to a ptr seems to fix the issue but would remove that functionality, will look into other fixes.

**Comment by spacepluk** [comment]
It's strange, if I try `nimble build` on a project with just the imgui example it fails. But compiling directly with: `nim c -d:opengl_debug -r src/main.nim` works fine.

**Comment by lmariscal** [comment]
It is because using the C++ backend uses code that is not complying with C++ but with C, so it breaks. If you are able to use C for the meanwhile with a cimgui DLL it would solve the issue for you. This issue will take me a little while to solve properly since I'm a little busy with finals.

**Comment by spacepluk** [comment]
Sure, no rush I'm just playing with it.  Newbie question (if you have time) how did you map that error to that line of imgui.nim?

**Comment by lmariscal** [comment]
Sure no problem, the error mentions ImDrawChannel so I went a changed that data type to a ptr object so it would not generate a struct, and it solved the issue. I also crossed referenced this issue with https://github.com/status-im/nimbus/issues/2 which seems to be the same problem, so I know that clang++ is being pedantic with how it treats C code.

**Comment by Milerius** [comment]
I'm potentially interested of a fix it's possible

**Comment by lmariscal** [comment]
Fixed by https://github.com/nimgl/imgui/commit/76f4165b92a5575eedf703dff9b49783acf2862b.

**Comment by Yardanico** [comment]
Apparently, this error is back, although this time in different places:

```
/home/tiber/.cache/nim/thg_r/@mthg.nim.cpp:220:12: error: flexible array member 'Data' of type 'ImGuiTable []' with non-trivial destruction
ImGuiTable Data[SEQ_DECL_SIZE];
           ^
/home/tiber/.cache/nim/thg_r/@mthg.nim.cpp:302:17: error: flexible array member 'Data' of type 'ImGuiOldColumns []' with non-trivial destruction
ImGuiOldColumns Data[SEQ_DECL_SIZE];
```

I think those will be harder to fix, so it's not a big-priority thing really.

**Comment by jmgomez** [comment]
Im also getting a bunch of those in Mac:

```
/Volumes/Store/Dropbox/GameDev/UnrealProjects/NimForUEDemo/Plugins/NimForUE/.nimcache/guest/@m..@s..@s..@s..@s..@s..@s..@sNim@slib@ssystem.nim.cpp:600:9: error: flexible array member 'data' of type 'FString []' with non-trivial destruction
FString data[SEQ_DECL_SIZE];

```

Any idea of where I can start looking at?
